env: production

server:
  listen_ipv4: 127.0.0.1
  listen_ipv6:
  tls_cert_path:
  tls_key_path:
  port: 3000
  base_path: /
  public_url: http://localhost:3000

app:
  aggregation_time: '02:15'
  report_time_weekly: 'fri,18:00'
  heartbeat_max_age: 168h  # 1 week
  inactive_days: 7
  custom_languages:
    vue: Vue
    jsx: JSX
    svelte: Svelte

db:
  host:
  port:
  user:
  password:
  name: wakapi_testing.db
  dialect: sqlite3
  charset:
  max_conn: 1
  ssl: false
  automgirate_fail_silently: false

security:
  password_salt:
  insecure_cookies: true
  cookie_max_age: 172800
  allow_signup: true
  oidc_allow_signup: true
  expose_metrics: true
  signup_max_rate: 999/1s
  login_max_rate: 999/1s
  password_reset_max_rate: 999/1s

sentry:
  dsn:
  enable_tracing: false
  sample_rate:
  sample_rate_heartbeats:

mail:
  enabled: false
  provider: smtp
  sender: Wakapi <noreply@wakapi.dev>

  smtp:
    host:
    port:
    username:
    password:
    tls:
