name: ci
on:
  push:
  pull_request:

jobs:
  test:
    name: 'Unit- & API tests'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21
      id: go

    - name: Get dependencies
      run: go get

    - name: Unit Tests
      run: CGO_ENABLED=0 go test `go list ./... | grep -v 'github.com/muety/wakapi/scripts'` -run ./...  # skip scripts package, because not actually a package

    - name: API Tests
      run: |
        npm -g install newman
        ./testing/run_api_tests.sh

  migration:
    name: Migration tests
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        db: [sqlite, postgres, mysql, mariadb, mssql]

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21
      id: go

    - run: ./testing/run_api_tests.sh ${{ matrix.db }} --migration
